version: "3.8"
services:
    postgres:
        image: postgres:13.3
        container_name: postgres
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
        restart: always
        tty: true
        ports:
            - "5555:5432"
        user: root
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d
