version: "3.8"
services:
    api:
        build: .
        ports: 
            - 3000:3000
        tty: true
        restart: always
        environment:
            - DATABASE_DRIVER=postgres
            - DATABASE_HOST=127.0.0.1
            - DATABASE_PORT=5555
            - DATABASE_USER=root
            - DATABASE_PASSWORD=password
            - DATABASE_NAME=root
            - DATABASE_SSLMODE=disable
    postgres:
        image: postgres:13.3
        container_name: postgres
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=password
            - POSTGRES_INITDB_ARGS=--encoding=UTF-8
        ports:
            - "5555:5432"
        user: root
        tty: true
        restart: always
        volumes:
            # for Mac
            - ./sql:/docker-entrypoint-initdb.d
            # for Windows
            # SQL_PATH should set in this format: /c/path/to/sql
            - ${SQL_PATH}:/docker-entrypoint-initdb.d