basePath: /mgmt
definitions:
  managementapi.PostAPIRoutingReq:
    properties:
      api_key:
        type: string
      forward_url:
        type: string
      path:
        type: string
    type: object
  managementapi.Product:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      source:
        type: string
      thumbnail:
        type: string
    type: object
  managementapi.Products:
    properties:
      products:
        items:
          $ref: '#/definitions/managementapi.Product'
        type: array
    type: object
info:
  contact: {}
  description: This is an API that manages products.
  title: Management API
  version: "1.0"
paths:
  /api:
    post:
      description: Post a new API routing
      parameters:
      - description: routing parameters
        in: body
        name: api_routing
        required: true
        schema:
          $ref: '#/definitions/managementapi.PostAPIRoutingReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
      summary: Post API routing
  /health:
    get:
      description: checks whether this API works correctly or not
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: checks if API works
  /products:
    get:
      description: Get list of APIs and its information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/managementapi.Products'
      summary: Get list of products
swagger: "2.0"
